# Generated by Django 5.1.6 on 2025-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_status',
            field=models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], default='SILVER', max_length=100),
        ),
    ]
